AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for create an Secret for db credentials.
Parameters:
  stage:
    Type: String
    Default: prd
    AllowedValues:
      - prd
      - qa
      - dev
  project:
    Type: String
  account:
    Type: String
  DBClusterIdentifier:
    Type: String
  dbName:
    Type: String
  dbPort:
    Type: String

Resources:
  DBCredentialsSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "ause1-secm-${account}-${project}-db-credentials"
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate:
          Fn::Join:
            - ""
            - - '{"dbClusterIdentifier":"'
              - Ref: DBClusterIdentifier
              - '", "dbname":"'
              - Ref: dbName
              - '", "port":"'
              - Ref: dbPort
              - '", "username":"'
              - Ref: project
              - "_admin_"
              - Ref: stage
              - '"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '`|_"@\^/~'
      Tags:
        - Key: Name
          Value: !Sub "ause1-secm-${account}-${project}-db-credentials"

Outputs:
  DBCredentialsSecretARN:
    Description: DB Credentials Secret ARN.
    Value: !Ref DBCredentialsSecret
  DBCredentialsSecretName:
    Description: DB Credentials Secret Name
    Value: !Sub "ause1-secm-${account}-${project}-db-credentials"
