AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for create an Secret for db credentials.
Parameters:
  DBClusterArn:
    Type: String
  dbCredentialsSecretARN:
    Type: String
  ARNLambdaBack:
    Type: String
  ARNLambdaBackAuthorizer:
    Type: String

Resources:
  ResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId:
        Ref: dbCredentialsSecretARN
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Resource: "*"
            Action: secretsmanager:GetSecretValue
            Effect: Allow
            Condition:
              StringEquals:
                aws:sourceAccount:
                  Fn::Sub: ${AWS::AccountId}
              ArnLike:
                aws:sourceArn:
                  - !Ref DBClusterArn
            Principal:
              Service:
                - rds.amazonaws.com
